var adminApp=angular.module('sbAdminApp',[]);

adminApp.controller('HelpController',function($rootScope,$scope,$http){
	
	$scope.helpContents=[{
			"question":"Q1: How about changing my password?",
			"answer":"To change your CRO account password, sign in and then click the arrow next to your username (in the top corner) Next choose change password.<br/><br/> While changing the password need to provide a current password of account, new password and reenter the new password. Finally Click save, to change the password.<br/><br/> From next time onwards you have to provide a new password to login.",
		},{
			"question":"Q2: How I can report issues?",
			"answer":"Reports from customers on CRO help us identify and fix problems when something's not working. To report a problem: <br/><br/>1. Click report issue on left side menu. <br/><br/>Giving more detail Feature,Title and Description <b>(ex: adding a screenshot and description)</b> helps us find the problem.<br/><br/> Reporting issues when they happen helps make CRO better, and we appreciate the time it takes to give us this information.",
		},{
			"question":"Q3: How can I change my subscription settings?",
			"answer":"Your settings let you control, ease of records search and export. <br/><br/>You can view or change your account settings in the Settings page. To change a settings:<br/><br/> 1. Click settings on left side menu Under settings, <br/><br/>we have two types. 1. Lookup preference 2. Export Preference <br/><br/><b>1. Lookup preference</b> <br/><br/>It's used for records search <br/>- Default is subscribed counties <br/>- For preferred counties select counties and save. <br/><br/> <b>2. Export Preference</b> <br/><br/>It's used for export excel <br/>- Default is standard fields <br/>- For custom fields drag and drop fields and save.",
		},{
			"question":"Q4: How to Print Reports?",
			"answer":"<p><b>For printing reports from CRO, you require the following:</b></p><p><ul><li><b>Google Account</b></li><li><b>Google Chrome (For adding Printers)</b></li></ul></p><p>If you do not already have a Google account, please create one using the following link: <a href='https://accounts.google.com/SignUp?service=mail&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ltmpl=default' target='_blank'>https://accounts.google.com/SignUp?service=mail&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ltmpl=default.</a></p><p>Now add printers under your Google account.Printers can be added only by using Google Chrome. If it is not available in your system, please download and install the same using the following link: <a href='https://www.google.com/chrome/browser/features.html?brand=CHBD&gclid=CLzFoaqnhdICFc0TaAodGa4DGg' target='_blank'>https://www.google.com/chrome/browser/features.html?brand=CHBD&gclid=CLzFoaqnhdICFc0TaAodGa4DGg</a></p><p>Once you have Google Chrome in your system, simply follow the steps outlined below:</p><p><ol><li>Type (or copy & paste) <b>chrome://devices</b> in the Chrome browser</li><li>Under <b>Classic Printers,</b> click the <b>Add printers</b> button</li><li>If you are not already logged into your Google account, you will be asked to log into it. Once you are logged in, the list of printers connected under the local network will be displayed.If the printer is not in the list, Please add the printer by installing corresponding drivers in your local system</li><li>You may now select the desired printer from this list and click the <b>Add Printers</b> button to add it to your Google account</li><li>Once the required printers are added,you can click the <b>Manage Printers Link</b> to view all the printers under this Google account</li><li>Rename the printers if required. <b>(This is for you to identify the printers)</b></li><li>Now login into the CRO application and go to <b>Patients</b> (or) <b>Clients.</b></li><li>Select all the reports you want printed</li><li>Click the <b>Print Reports</b> Button</li><li>A popup window will appear for authentication of your Google account</li><li>Enter the Username and Password of your Google account. Once the account is authenticated, the list of printers associated with that account will be displayed</li><li>Now select the desired printer from the list and click the <b>Print</b> button</li><li>A popup window will now appear with the list of reports you selected for printing, along with the status of the print job for each report</li><li>Once the print jobs are completed, the pop up window can be closed</li></ol></p>",
		}];

	if($rootScope.isAdmin==2||$rootScope.isAdmin==4){
		$scope.printAnswer="<p><b>For printing reports from CRO, you require the following:</b></p><p><ul><li><b>Google Account</b></li><li><b>Google Chrome (For adding Printers)</b></li></ul></p><p>If you do not already have a Google account, please create one using the following link: <a href='https://accounts.google.com/SignUp?service=mail&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ltmpl=default' target='_blank'>https://accounts.google.com/SignUp?service=mail&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ltmpl=default.</a></p><p>Now add printers under your Google account.Printers can be added only by using Google Chrome. If it is not available in your system, please download and install the same using the following link: <a href='https://www.google.com/chrome/browser/features.html?brand=CHBD&gclid=CLzFoaqnhdICFc0TaAodGa4DGg' target='_blank'>https://www.google.com/chrome/browser/features.html?brand=CHBD&gclid=CLzFoaqnhdICFc0TaAodGa4DGg</a></p><p>Once you have Google Chrome in your system, simply follow the steps outlined below:</p><p><ol><li>Type (or copy & paste) <b>chrome://devices</b> in the Chrome browser</li><li>Under <b>Classic Printers,</b> click the <b>Add printers</b> button</li><li>If you are not already logged into your Google account, you will be asked to log into it. Once you are logged in, the list of printers connected under the local network will be displayed.If the printer is not in the list, Please add the printer by installing corresponding drivers in your local system</li><li>You may now select the desired printer from this list and click the <b>Add Printers</b> button to add it to your Google account</li><li>Once the required printers are added,you can click the <b>Manage Printers Link</b> to view all the printers under this Google account</li><li>Rename the printers if required. <b>(This is for you to identify the printers)</b></li><li>Now login into the CRO application and go to <b>Patients</b></li><li>Select all the reports you want printed</li><li>Click the <b>Print Reports</b> Button</li><li>A popup window will appear for authentication of your Google account</li><li>Enter the Username and Password of your Google account. Once the account is authenticated, the list of printers associated with that account will be displayed</li><li>Now select the desired printer from the list and click the <b>Print</b> button</li><li>A popup window will now appear with the list of reports you selected for printing, along with the status of the print job for each report</li><li>Once the print jobs are completed, the pop up window can be closed</li></ol></p>";
	}else if($rootScope.isAdmin==3||$rootScope.isAdmin==5){
		$scope.printAnswer="<p><b>For printing reports from CRO, you require the following:</b></p><p><ul><li><b>Google Account</b></li><li><b>Google Chrome (For adding Printers)</b></li></ul></p><p>If you do not already have a Google account, please create one using the following link: <a href='https://accounts.google.com/SignUp?service=mail&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ltmpl=default' target='_blank'>https://accounts.google.com/SignUp?service=mail&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ltmpl=default.</a></p><p>Now add printers under your Google account.Printers can be added only by using Google Chrome. If it is not available in your system, please download and install the same using the following link: <a href='https://www.google.com/chrome/browser/features.html?brand=CHBD&gclid=CLzFoaqnhdICFc0TaAodGa4DGg' target='_blank'>https://www.google.com/chrome/browser/features.html?brand=CHBD&gclid=CLzFoaqnhdICFc0TaAodGa4DGg</a></p><p>Once you have Google Chrome in your system, simply follow the steps outlined below:</p><p><ol><li>Type (or copy & paste) <b>chrome://devices</b> in the Chrome browser</li><li>Under <b>Classic Printers,</b> click the <b>Add printers</b> button</li><li>If you are not already logged into your Google account, you will be asked to log into it. Once you are logged in, the list of printers connected under the local network will be displayed.If the printer is not in the list, Please add the printer by installing corresponding drivers in your local system</li><li>You may now select the desired printer from this list and click the <b>Add Printers</b> button to add it to your Google account</li><li>Once the required printers are added,you can click the <b>Manage Printers Link</b> to view all the printers under this Google account</li><li>Rename the printers if required. <b>(This is for you to identify the printers)</b></li><li>Now login into the CRO application and go to <b>Clients</b></li><li>Select all the reports you want printed</li><li>Click the <b>Print Reports</b> Button</li><li>A popup window will appear for authentication of your Google account</li><li>Enter the Username and Password of your Google account. Once the account is authenticated, the list of printers associated with that account will be displayed</li><li>Now select the desired printer from the list and click the <b>Print</b> button</li><li>A popup window will now appear with the list of reports you selected for printing, along with the status of the print job for each report</li><li>Once the print jobs are completed, the pop up window can be closed</li></ol></p>";
	}
	
	if($rootScope.isAdmin==2||$rootScope.isAdmin==3){
		$scope.helpContents=[{
			"question":"Q1: How about changing my password?",
			"answer":"To change your CRO account password, sign in and then click the arrow next to your username (in the top corner) Next choose change password.<br/><br/> While changing the password need to provide a current password of account, new password and reenter the new password. Finally Click save, to change the password.<br/><br/> From next time onwards you have to provide a new password to login.",
		},{
			"question":"Q2: How I can report issues?",
			"answer":"Reports from customers on CRO help us identify and fix problems when something's not working. To report a problem: <br/><br/>1. Click report issue on left side menu. <br/><br/>Giving more detail Feature,Title and Description <b>(ex: adding a screenshot and description)</b> helps us find the problem.<br/><br/> Reporting issues when they happen helps make CRO better, and we appreciate the time it takes to give us this information.",
		},{
			"question":"Q3: How can I change my subscription settings?",
			"answer":"Your settings let you control, ease of records search and export. <br/><br/>You can view or change your account settings in the Settings page. To change a settings:<br/><br/> 1. Click settings on left side menu Under settings, <br/><br/>we have two types. 1. Lookup preference 2. Export Preference <br/><br/><b>1. Lookup preference</b> <br/><br/>It's used for records search <br/>- Default is subscribed counties <br/>- For preferred counties select counties and save. <br/><br/> <b>2. Export Preference</b> <br/><br/>It's used for export excel <br/>- Default is standard fields <br/>- For custom fields drag and drop fields and save.",
		},{
			"question":"Q4: How to Print Reports?",
			"answer":$scope.printAnswer,
		}];
	}else if($rootScope.isAdmin==4||$rootScope.isAdmin==5){
		$scope.helpContents=[{
			"question":"Q1: How about changing my password?",
			"answer":"To change your CRO account password, sign in and then click the arrow next to your username (in the top corner) Next choose change password.<br/><br/> While changing the password need to provide a current password of account, new password and reenter the new password. Finally Click save, to change the password.<br/><br/> From next time onwards you have to provide a new password to login.",
		},{
			"question":"Q2: How I can report issues?",
			"answer":"Reports from customers on CRO help us identify and fix problems when something's not working. To report a problem: <br/><br/>1. Click report issue on left side menu. <br/><br/>Giving more detail Feature,Title and Description <b>(ex: adding a screenshot and description)</b> helps us find the problem.<br/><br/> Reporting issues when they happen helps make CRO better, and we appreciate the time it takes to give us this information.",
		},{
			"question":"Q3: How can I change my subscription settings?",
			"answer":"Your settings let you control, ease of records search and export. <br/><br/>You can view or change your account settings by <b>contact admin</b>.",
		},{
			"question":"Q4: How to Print Reports?",
			"answer":$scope.printAnswer,
		}];
	}
	 
});

//html filter (render text as html)
adminApp.filter('html', ['$sce', function ($sce) {
    return function (text) {
        return $sce.trustAsHtml(text);
    };
}]);