package com.deemsys.project.entity;

// Generated 22 Jan, 2018 6:51:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActivityLogs generated by hbm2java
 */
@Entity
@Table(name = "activity_logs", catalog = "injuryreportsdbpro")
public class ActivityLogs implements java.io.Serializable {

	private String sessionId;
	private IpAccessList ipAccessList;
	private Users usersByLoginId;
	private Activity activity;
	private Users usersByPrimaryId;
	private Date accessDate;
	private String accessInTime;
	private String accessOutTime;
	private Integer status;

	public ActivityLogs() {
	}

	public ActivityLogs(String sessionId) {
		this.sessionId = sessionId;
	}

	public ActivityLogs(String sessionId, IpAccessList ipAccessList,
			Users usersByLoginId, Activity activity, Users usersByPrimaryId,
			Date accessDate, String accessInTime, String accessOutTime,
			Integer status) {
		this.sessionId = sessionId;
		this.ipAccessList = ipAccessList;
		this.usersByLoginId = usersByLoginId;
		this.activity = activity;
		this.usersByPrimaryId = usersByPrimaryId;
		this.accessDate = accessDate;
		this.accessInTime = accessInTime;
		this.accessOutTime = accessOutTime;
		this.status = status;
	}

	@Id
	@Column(name = "session_id", unique = true, nullable = false, length = 32)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "primary_id", referencedColumnName = "primary_login_id"),
			@JoinColumn(name = "ip_address", referencedColumnName = "ip_address") })
	public IpAccessList getIpAccessList() {
		return this.ipAccessList;
	}

	public void setIpAccessList(IpAccessList ipAccessList) {
		this.ipAccessList = ipAccessList;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "login_id")
	public Users getUsersByLoginId() {
		return this.usersByLoginId;
	}

	public void setUsersByLoginId(Users usersByLoginId) {
		this.usersByLoginId = usersByLoginId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "activity_id")
	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "primary_id", insertable = false, updatable = false)
	public Users getUsersByPrimaryId() {
		return this.usersByPrimaryId;
	}

	public void setUsersByPrimaryId(Users usersByPrimaryId) {
		this.usersByPrimaryId = usersByPrimaryId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "access_date", length = 10)
	public Date getAccessDate() {
		return this.accessDate;
	}

	public void setAccessDate(Date accessDate) {
		this.accessDate = accessDate;
	}

	@Column(name = "access_in_time", length = 45)
	public String getAccessInTime() {
		return this.accessInTime;
	}

	public void setAccessInTime(String accessInTime) {
		this.accessInTime = accessInTime;
	}

	@Column(name = "access_out_time", length = 45)
	public String getAccessOutTime() {
		return this.accessOutTime;
	}

	public void setAccessOutTime(String accessOutTime) {
		this.accessOutTime = accessOutTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
