package com.deemsys.project.entity;

// Generated Aug 6, 2015 2:51:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Appointments generated by hbm2java
 */
@Entity
@Table(name = "Appointments", catalog = "injury")
public class Appointments implements java.io.Serializable {

	private Integer id;
	private Patients patients;
	private Date scheduledDate;
	private String notes;
	private Integer status;
	private Set<CallLogs> callLogses = new HashSet<CallLogs>(0);

	public Appointments() {
	}

	public Appointments(Patients patients) {
		this.patients = patients;
	}

	public Appointments(Patients patients, Date scheduledDate, String notes,
			Integer status, Set<CallLogs> callLogses) {
		this.patients = patients;
		this.scheduledDate = scheduledDate;
		this.notes = notes;
		this.status = status;
		this.callLogses = callLogses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false)
	public Patients getPatients() {
		return this.patients;
	}

	public void setPatients(Patients patients) {
		this.patients = patients;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "scheduled_date", length = 10)
	public Date getScheduledDate() {
		return this.scheduledDate;
	}

	public void setScheduledDate(Date scheduledDate) {
		this.scheduledDate = scheduledDate;
	}

	@Column(name = "notes", length = 600)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appointments")
	public Set<CallLogs> getCallLogses() {
		return this.callLogses;
	}

	public void setCallLogses(Set<CallLogs> callLogses) {
		this.callLogses = callLogses;
	}

}
