package com.deemsys.project.entity;

// Generated Mar 16, 2016 12:32:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Appointments generated by hbm2java
 */
@Entity
@Table(name = "appointments", catalog = "injury_latest")
public class Appointments implements java.io.Serializable {

	private Long appointmentId;
	private CallLog callLog;
	private Date scheduledDate;
	private String notes;
	private Integer status;

	public Appointments() {
	}

	public Appointments(long appointmentId) {
		this.appointmentId = appointmentId;
	}

	public Appointments(long appointmentId, CallLog callLog,
			Date scheduledDate, String notes, Integer status) {
		this.appointmentId = appointmentId;
		this.callLog = callLog;
		this.scheduledDate = scheduledDate;
		this.notes = notes;
		this.status = status;
	}

	@Id
	@Column(name = "appointment_id", unique = true, nullable = false)
	public Long getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(Long appointmentId) {
		this.appointmentId = appointmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "call_log_id")
	public CallLog getCallLog() {
		return this.callLog;
	}

	public void setCallLog(CallLog callLog) {
		this.callLog = callLog;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "scheduled_date", length = 10)
	public Date getScheduledDate() {
		return this.scheduledDate;
	}

	public void setScheduledDate(Date scheduledDate) {
		this.scheduledDate = scheduledDate;
	}

	@Column(name = "notes", length = 300)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
