package com.deemsys.project.entity;

// Generated Jul 3, 2015 12:57:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Appointments generated by hbm2java
 */
@Entity
@Table(name = "Appointments", catalog = "injury")
public class Appointments implements java.io.Serializable {

	private Integer id;
	private Staff staff;
	private Doctors doctors;
	private Patients patients;
	private Date scheduledDate;
	private String notes;

	public Appointments() {
	}

	public Appointments(Staff staff, Doctors doctors, Patients patients) {
		this.staff = staff;
		this.doctors = doctors;
		this.patients = patients;
	}

	public Appointments(Staff staff, Doctors doctors, Patients patients,
			Date scheduledDate, String notes) {
		this.staff = staff;
		this.doctors = doctors;
		this.patients = patients;
		this.scheduledDate = scheduledDate;
		this.notes = notes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "caller_id", nullable = false)
	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctor_id", nullable = false)
	public Doctors getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Doctors doctors) {
		this.doctors = doctors;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false)
	public Patients getPatients() {
		return this.patients;
	}

	public void setPatients(Patients patients) {
		this.patients = patients;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "scheduled_date", length = 10)
	public Date getScheduledDate() {
		return this.scheduledDate;
	}

	public void setScheduledDate(Date scheduledDate) {
		this.scheduledDate = scheduledDate;
	}

	@Column(name = "notes", length = 600)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
