package com.deemsys.project.entity;

// Generated Mar 16, 2016 12:32:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CallerCountyMap generated by hbm2java
 */
@Entity
@Table(name = "caller_county_map", catalog = "injury_latest")
public class CallerCountyMap implements java.io.Serializable {

	private CallerCountyMapId id;
	private County county;
	private Caller caller;
	private Integer status;

	public CallerCountyMap() {
	}

	public CallerCountyMap(CallerCountyMapId id, County county, Caller caller) {
		this.id = id;
		this.county = county;
		this.caller = caller;
	}

	public CallerCountyMap(CallerCountyMapId id, County county, Caller caller,
			Integer status) {
		this.id = id;
		this.county = county;
		this.caller = caller;
		this.status = status;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "callerId", column = @Column(name = "caller_id", nullable = false)),
			@AttributeOverride(name = "countyId", column = @Column(name = "county_id", nullable = false)) })
	public CallerCountyMapId getId() {
		return this.id;
	}

	public void setId(CallerCountyMapId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "county_id", nullable = false, insertable = false, updatable = false)
	public County getCounty() {
		return this.county;
	}

	public void setCounty(County county) {
		this.county = county;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "caller_id", nullable = false, insertable = false, updatable = false)
	public Caller getCaller() {
		return this.caller;
	}

	public void setCaller(Caller caller) {
		this.caller = caller;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
