package com.deemsys.project.entity;

// Generated Jun 21, 2016 4:47:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContactUs generated by hbm2java
 */
@Entity
@Table(name = "contact_us", catalog = "injuryreportsdb")
public class ContactUs implements java.io.Serializable {

	private Integer id;
	private String firstName;
	private String lastName;
	private String email;
	private String phoneNumber;
	private String firmName;
	private Date addedDateTime;
	private Integer status;
	private Set<ContactUsLog> contactUsLogs = new HashSet<ContactUsLog>(0);

	public ContactUs() {
	}

	public ContactUs(String firstName, String lastName, String email,
			String phoneNumber, String firmName, Date addedDateTime,
			Integer status, Set<ContactUsLog> contactUsLogs) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.firmName = firmName;
		this.addedDateTime = addedDateTime;
		this.status = status;
		this.contactUsLogs = contactUsLogs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "first_name", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", length = 60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone_number", length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "firm_name", length = 150)
	public String getFirmName() {
		return this.firmName;
	}

	public void setFirmName(String firmName) {
		this.firmName = firmName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "added_date_time", length = 19)
	public Date getAddedDateTime() {
		return this.addedDateTime;
	}

	public void setAddedDateTime(Date addedDateTime) {
		this.addedDateTime = addedDateTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactUs", cascade=CascadeType.REMOVE)
	public Set<ContactUsLog> getContactUsLogs() {
		return this.contactUsLogs;
	}

	public void setContactUsLogs(Set<ContactUsLog> contactUsLogs) {
		this.contactUsLogs = contactUsLogs;
	}

}
