package com.deemsys.project.entity;

// Generated Feb 13, 2016 12:33:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * County generated by hbm2java
 */
@Entity
@Table(name = "county", catalog = "injury_new")
public class County implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer status;
	private Set<LawyerCountyMapping> lawyerCountyMappings = new HashSet<LawyerCountyMapping>(
			0);

	public County() {
	}

	public County(String name, Integer status,
			Set<LawyerCountyMapping> lawyerCountyMappings) {
		this.name = name;
		this.status = status;
		this.lawyerCountyMappings = lawyerCountyMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "county")
	public Set<LawyerCountyMapping> getLawyerCountyMappings() {
		return this.lawyerCountyMappings;
	}

	public void setLawyerCountyMappings(
			Set<LawyerCountyMapping> lawyerCountyMappings) {
		this.lawyerCountyMappings = lawyerCountyMappings;
	}

}
