package com.deemsys.project.entity;

// Generated Mar 16, 2016 12:32:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * County generated by hbm2java
 */
@Entity
@Table(name = "county", catalog = "injury_latest")
public class County implements java.io.Serializable {

	private Integer countyId;
	private String name;
	private Integer status;
	private Set<LawyerAdminCountyMap> lawyerAdminCountyMaps = new HashSet<LawyerAdminCountyMap>(
			0);
	private Set<LawyerCountyMap> lawyerCountyMaps = new HashSet<LawyerCountyMap>(
			0);
	private Set<CallerCountyMap> callerCountyMaps = new HashSet<CallerCountyMap>(
			0);
	private Set<CallerAdminCountyMap> callerAdminCountyMaps = new HashSet<CallerAdminCountyMap>(
			0);
	private Set<CrashReport> crashReports = new HashSet<CrashReport>(
			0);
	public County() {
	}

	public County(String name, Integer status,
			Set<LawyerAdminCountyMap> lawyerAdminCountyMaps,
			Set<LawyerCountyMap> lawyerCountyMaps,
			Set<CallerCountyMap> callerCountyMaps,
			Set<CallerAdminCountyMap> callerAdminCountyMaps) {
		this.name = name;
		this.status = status;
		this.lawyerAdminCountyMaps = lawyerAdminCountyMaps;
		this.lawyerCountyMaps = lawyerCountyMaps;
		this.callerCountyMaps = callerCountyMaps;
		this.callerAdminCountyMaps = callerAdminCountyMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "county_id", unique = true, nullable = false)
	public Integer getCountyId() {
		return this.countyId;
	}

	public void setCountyId(Integer countyId) {
		this.countyId = countyId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "county")
	public Set<LawyerAdminCountyMap> getLawyerAdminCountyMaps() {
		return this.lawyerAdminCountyMaps;
	}

	public void setLawyerAdminCountyMaps(
			Set<LawyerAdminCountyMap> lawyerAdminCountyMaps) {
		this.lawyerAdminCountyMaps = lawyerAdminCountyMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "county")
	public Set<LawyerCountyMap> getLawyerCountyMaps() {
		return this.lawyerCountyMaps;
	}

	public void setLawyerCountyMaps(Set<LawyerCountyMap> lawyerCountyMaps) {
		this.lawyerCountyMaps = lawyerCountyMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "county")
	public Set<CallerCountyMap> getCallerCountyMaps() {
		return this.callerCountyMaps;
	}

	public void setCallerCountyMaps(Set<CallerCountyMap> callerCountyMaps) {
		this.callerCountyMaps = callerCountyMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "county")
	public Set<CallerAdminCountyMap> getCallerAdminCountyMaps() {
		return this.callerAdminCountyMaps;
	}

	public void setCallerAdminCountyMaps(
			Set<CallerAdminCountyMap> callerAdminCountyMaps) {
		this.callerAdminCountyMaps = callerAdminCountyMaps;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "county")
	public Set<CrashReport> getCrashReports() {
		return this.crashReports;
	}

	public void setCrashReports(
			Set<CrashReport> crashReports) {
		this.crashReports = crashReports;
	}

}
