package com.deemsys.project.entity;

// Generated Mar 16, 2016 12:32:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrashReport generated by hbm2java
 */
@Entity
@Table(name = "crash_report", catalog = "injury_latest")
public class CrashReport implements java.io.Serializable {

	private Long crashReportId;
	private CrashReportError crashReportError;
	private String localReportNumber;
	private String crashId;
	private String crashDate;
	private String county;
	private String addedDate;
	private String filePath;
	private Integer status;

	public CrashReport() {
	}

	public CrashReport(CrashReportError crashReportError,
			String localReportNumber, String crashId, String crashDate,
			String county, String addedDate, String filePath, Integer status) {
		this.crashReportError = crashReportError;
		this.localReportNumber = localReportNumber;
		this.crashId = crashId;
		this.crashDate = crashDate;
		this.county = county;
		this.addedDate = addedDate;
		this.filePath = filePath;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "crash_report_id", unique = true, nullable = false)
	public Long getCrashReportId() {
		return this.crashReportId;
	}

	public void setCrashReportId(Long crashReportId) {
		this.crashReportId = crashReportId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "error_id")
	public CrashReportError getCrashReportError() {
		return this.crashReportError;
	}

	public void setCrashReportError(CrashReportError crashReportError) {
		this.crashReportError = crashReportError;
	}

	@Column(name = "local_report_number", length = 45)
	public String getLocalReportNumber() {
		return this.localReportNumber;
	}

	public void setLocalReportNumber(String localReportNumber) {
		this.localReportNumber = localReportNumber;
	}

	@Column(name = "crash_id", length = 45)
	public String getCrashId() {
		return this.crashId;
	}

	public void setCrashId(String crashId) {
		this.crashId = crashId;
	}

	@Column(name = "crash_date", length = 45)
	public String getCrashDate() {
		return this.crashDate;
	}

	public void setCrashDate(String crashDate) {
		this.crashDate = crashDate;
	}

	@Column(name = "county", length = 45)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "added_date", length = 45)
	public String getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(String addedDate) {
		this.addedDate = addedDate;
	}

	@Column(name = "file_path", length = 100)
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
