package com.deemsys.project.entity;

// Generated Sep 7, 2015 4:36:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.deemsys.project.entity.Patients;

/**
 * Doctors generated by hbm2java
 */
@Entity
@Table(name = "Doctors", catalog = "injury")
public class Doctors implements java.io.Serializable {

	private Integer id;
	private String clinicName;
	private String doctorName;
	private String address;
	private String city;
	private String country;
	private String state;
	private String county;
	private String zip;
	private String officeNumber;
	private String faxNumber;
	private String workingDays;
	private Date officeHoursFromTime;
	private Date officeHoursToTime;
	private String direction;
	private String notes;
	private Set<Patients> patientses = new HashSet<Patients>(0);
	public Doctors() {
	}

	public Doctors(String clinicName, String doctorName, String address,
			String city, String country, String state, String county, String zip,
			String officeNumber, String faxNumber, String workingDays,
			Date officeHoursFromTime, Date officeHoursToTime, String direction,
			String notes, Set<Patients> patientses) {
		this.clinicName = clinicName;
		this.doctorName = doctorName;
		this.address = address;
		this.city = city;
		this.country = country;
		this.state = state;
		this.county = county;
		this.zip = zip;
		this.officeNumber = officeNumber;
		this.faxNumber = faxNumber;
		this.workingDays = workingDays;
		this.officeHoursFromTime = officeHoursFromTime;
		this.officeHoursToTime = officeHoursToTime;
		this.direction = direction;
		this.notes = notes;
		this.patientses = patientses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "clinic_name", length = 100)
	public String getClinicName() {
		return this.clinicName;
	}

	public void setClinicName(String clinicName) {
		this.clinicName = clinicName;
	}

	@Column(name = "doctor_name", length = 60)
	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "county", length = 45)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}
	
	@Column(name = "zip", length = 10)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "office_number", length = 45)
	public String getOfficeNumber() {
		return this.officeNumber;
	}

	public void setOfficeNumber(String officeNumber) {
		this.officeNumber = officeNumber;
	}

	@Column(name = "fax_number", length = 45)
	public String getFaxNumber() {
		return this.faxNumber;
	}

	public void setFaxNumber(String faxNumber) {
		this.faxNumber = faxNumber;
	}

	@Column(name = "working_days", length = 45)
	public String getWorkingDays() {
		return this.workingDays;
	}

	public void setWorkingDays(String workingDays) {
		this.workingDays = workingDays;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "office_hours_from_time", length = 8)
	public Date getOfficeHoursFromTime() {
		return this.officeHoursFromTime;
	}

	public void setOfficeHoursFromTime(Date officeHoursFromTime) {
		this.officeHoursFromTime = officeHoursFromTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "office_hours_to_time", length = 8)
	public Date getOfficeHoursToTime() {
		return this.officeHoursToTime;
	}

	public void setOfficeHoursToTime(Date officeHoursToTime) {
		this.officeHoursToTime = officeHoursToTime;
	}

	@Column(name = "direction", length = 65535)
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	@Column(name = "notes", length = 65535)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doctors")
	public Set<Patients> getPatientses() {
		return this.patientses;
	}

	public void setPatientses(Set<Patients> patientses) {
		this.patientses = patientses;
	}

}
