package com.deemsys.project.entity;

// Generated Mar 16, 2016 12:32:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientLawyerAdminMapId generated by hbm2java
 */
@Embeddable
public class PatientLawyerAdminMapId implements java.io.Serializable {

	private String patientId;
	private int lawyerAdminId;

	public PatientLawyerAdminMapId() {
	}

	public PatientLawyerAdminMapId(String patientId, int lawyerAdminId) {
		this.patientId = patientId;
		this.lawyerAdminId = lawyerAdminId;
	}

	@Column(name = "patient_id", nullable = false)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "lawyer_admin_id", nullable = false)
	public int getLawyerAdminId() {
		return this.lawyerAdminId;
	}

	public void setLawyerAdminId(int lawyerAdminId) {
		this.lawyerAdminId = lawyerAdminId;
	}
}
