package com.deemsys.project.entity;

// Generated Mar 16, 2016 12:32:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientCallerAdminMapId generated by hbm2java
 */
@Embeddable
public class PatientCallerAdminMapId implements java.io.Serializable {

	private String patientId;
	private int callerAdminId;

	public PatientCallerAdminMapId() {
	}

	public PatientCallerAdminMapId(String patientId, int callerAdminId) {
		this.patientId = patientId;
		this.callerAdminId = callerAdminId;
	}

	@Column(name = "patient_id", nullable = false)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "caller_admin_id", nullable = false)
	public int getCallerAdminId() {
		return this.callerAdminId;
	}

	public void setCallerAdminId(int callerAdminId) {
		this.callerAdminId = callerAdminId;
	}

	
}
