package com.deemsys.project.entity;

// Generated Aug 6, 2015 2:51:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Patients generated by hbm2java
 */
@Entity
@Table(name = "Patients", catalog = "injurytest")
public class Patients implements java.io.Serializable {

	private Integer id;
	private Staff staff;
	private Doctors doctors;
	private String localReportNumber;
	private String crashSeverity;
	private String reportingAgencyName;
	private String numberOfUnits;
	private String unitInError;
	private String country;
	private String cityVillageTownship;
	private String crashDate;
	private String timeOfCrash;
	private String localReportNumber1;
	private String unitNumber;
	private String name;
	private String dateOfBirth;
	private String gender;
	private String address;
	private String phoneNumber;
	private String injuries;
	private String emsAgency;
	private String medicalFacility;
	private String localReportNumber2;
	private String unitInError1;
	private String unitNumber1;
	private String ownerName;
	private String ownerPhoneNumber;
	private String damageScale;
	private String proofOfInsurance;
	private String insuranceCompany;
	private String policyNumber;
	private String crashReportFileName;
	private Set<Appointments> appointmentses = new HashSet<Appointments>(0);
	private Set<CallLogs> callLogses = new HashSet<CallLogs>(0);

	public Patients() {
	}

	public Patients(Staff staff, Doctors doctors, String localReportNumber,
			String crashSeverity, String reportingAgencyName,
			String numberOfUnits, String unitInError, String country,
			String cityVillageTownship, String crashDate, String timeOfCrash,
			String localReportNumber1, String unitNumber, String name,
			String dateOfBirth, String gender, String address,
			String phoneNumber, String injuries, String emsAgency,
			String medicalFacility, String localReportNumber2,
			String unitInError1, String unitNumber1, String ownerName,
			String ownerPhoneNumber, String damageScale,
			String proofOfInsurance,String insuranceCompany,String policyNumber,String crashReportFileName) {
		this.staff = staff;
		this.doctors = doctors;
		this.localReportNumber = localReportNumber;
		this.crashSeverity = crashSeverity;
		this.reportingAgencyName = reportingAgencyName;
		this.numberOfUnits = numberOfUnits;
		this.unitInError = unitInError;
		this.country = country;
		this.cityVillageTownship = cityVillageTownship;
		this.crashDate = crashDate;
		this.timeOfCrash = timeOfCrash;
		this.localReportNumber1 = localReportNumber1;
		this.unitNumber = unitNumber;
		this.name = name;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.injuries = injuries;
		this.emsAgency = emsAgency;
		this.medicalFacility = medicalFacility;
		this.localReportNumber2 = localReportNumber2;
		this.unitInError1 = unitInError1;
		this.unitNumber1 = unitNumber1;
		this.ownerName = ownerName;
		this.ownerPhoneNumber = ownerPhoneNumber;
		this.damageScale = damageScale;
		this.proofOfInsurance = proofOfInsurance;
		this.insuranceCompany = insuranceCompany;
		this.policyNumber = policyNumber;
		this.crashReportFileName=crashReportFileName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "caller_id",nullable=true)
	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctor_id", nullable=true)
	public Doctors getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Doctors doctors) {
		this.doctors = doctors;
	}

	@Column(name = "local_report_number", length = 100)
	public String getLocalReportNumber() {
		return this.localReportNumber;
	}

	public void setLocalReportNumber(String localReportNumber) {
		this.localReportNumber = localReportNumber;
	}

	@Column(name = "crash_severity")
	public String getCrashSeverity() {
		return this.crashSeverity;
	}

	public void setCrashSeverity(String crashSeverity) {
		this.crashSeverity = crashSeverity;
	}

	@Column(name = "reporting_agency_name", length = 100)
	public String getReportingAgencyName() {
		return this.reportingAgencyName;
	}

	public void setReportingAgencyName(String reportingAgencyName) {
		this.reportingAgencyName = reportingAgencyName;
	}

	@Column(name = "number_of_units")
	public String getNumberOfUnits() {
		return this.numberOfUnits;
	}

	public void setNumberOfUnits(String numberOfUnits) {
		this.numberOfUnits = numberOfUnits;
	}

	@Column(name = "unit_in_error")
	public String getUnitInError() {
		return this.unitInError;
	}

	public void setUnitInError(String unitInError) {
		this.unitInError = unitInError;
	}

	@Column(name = "country",length=100)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "city_village_township", length = 100)
	public String getCityVillageTownship() {
		return this.cityVillageTownship;
	}

	public void setCityVillageTownship(String cityVillageTownship) {
		this.cityVillageTownship = cityVillageTownship;
	}


	@Column(name = "crash_date", length = 100)
	public String getCrashDate() {
		return this.crashDate;
	}

	public void setCrashDate(String crashDate) {
		this.crashDate = crashDate;
	}

	@Column(name = "time_of_crash", length = 100)
	public String getTimeOfCrash() {
		return this.timeOfCrash;
	}

	public void setTimeOfCrash(String timeOfCrash) {
		this.timeOfCrash = timeOfCrash;
	}

	@Column(name = "local_report_number1", length = 100)
	public String getLocalReportNumber1() {
		return this.localReportNumber1;
	}

	public void setLocalReportNumber1(String localReportNumber1) {
		this.localReportNumber1 = localReportNumber1;
	}

	@Column(name = "unit_number")
	public String getUnitNumber() {
		return this.unitNumber;
	}

	public void setUnitNumber(String unitNumber) {
		this.unitNumber = unitNumber;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "date_of_birth", length = 100)
	public String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "gender",length = 100)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "address", length = 300)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone_number", length = 100)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "injuries")
	public String getInjuries() {
		return this.injuries;
	}

	public void setInjuries(String injuries) {
		this.injuries = injuries;
	}

	@Column(name = "ems_agency", length = 100)
	public String getEmsAgency() {
		return this.emsAgency;
	}

	public void setEmsAgency(String emsAgency) {
		this.emsAgency = emsAgency;
	}

	@Column(name = "medical_facility", length = 100)
	public String getMedicalFacility() {
		return this.medicalFacility;
	}

	public void setMedicalFacility(String medicalFacility) {
		this.medicalFacility = medicalFacility;
	}

	@Column(name = "local_report_number2", length = 100)
	public String getLocalReportNumber2() {
		return this.localReportNumber2;
	}

	public void setLocalReportNumber2(String localReportNumber2) {
		this.localReportNumber2 = localReportNumber2;
	}

	@Column(name = "unit_in_error1")
	public String getUnitInError1() {
		return this.unitInError1;
	}

	public void setUnitInError1(String unitInError1) {
		this.unitInError1 = unitInError1;
	}

	@Column(name = "unit_number1")
	public String getUnitNumber1() {
		return this.unitNumber1;
	}

	public void setUnitNumber1(String unitNumber1) {
		this.unitNumber1 = unitNumber1;
	}

	@Column(name = "owner_name", length = 100)
	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	@Column(name = "owner_phone_number", length = 100)
	public String getOwnerPhoneNumber() {
		return this.ownerPhoneNumber;
	}

	public void setOwnerPhoneNumber(String ownerPhoneNumber) {
		this.ownerPhoneNumber = ownerPhoneNumber;
	}

	@Column(name = "damage_scale")
	public String getDamageScale() {
		return this.damageScale;
	}

	public void setDamageScale(String damageScale) {
		this.damageScale = damageScale;
	}

	@Column(name = "proof_of_insurance",length = 100)
	public String getProofOfInsurance() {
		return this.proofOfInsurance;
	}

	public void setProofOfInsurance(String proofOfInsurance) {
		this.proofOfInsurance = proofOfInsurance;
	}
	
	@Column(name = "insurance_company", length = 100)
	public String getInsuranceCompany() {
		return this.insuranceCompany;
	}

	public void setInsuranceCompany(String insuranceCompany) {
		this.insuranceCompany = insuranceCompany;
	}
	
	@Column(name = "policy_number", length = 100)
	public String getPolicyNumber() {
		return this.policyNumber;
	}

	@Column(name = "crash_report_file_name", length = 800)
	public String getCrashReportFileName() {
		return crashReportFileName;
	}

	public void setCrashReportFileName(String crashReportFileName) {
		this.crashReportFileName = crashReportFileName;
	}

	public void setPolicyNumber(String policyNumber) {
		this.policyNumber = policyNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patients")
	public Set<Appointments> getAppointmentses() {
		return this.appointmentses;
	}

	public void setAppointmentses(Set<Appointments> appointmentses) {
		this.appointmentses = appointmentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patients")
	public Set<CallLogs> getCallLogses() {
		return this.callLogses;
	}

	public void setCallLogses(Set<CallLogs> callLogses) {
		this.callLogses = callLogses;
	}

}
