package com.deemsys.project.entity;
// Generated Jul 18, 2015 10:49:05 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Patients generated by hbm2java
 */
@Entity
@Table(name = "Patients", catalog = "injury")
public class Patients implements java.io.Serializable {

	private Integer id;
	private Staff staff;
	private Doctors doctors;
	private String firstName;
	private String lastName;
	private String reportNumber;
	private String phoneNumber;
	private String address;
	private String injury;
	private Date dateOfCrash;
	private String otherPassengers;
	private String notes;
	private Set<Appointments> appointmentses = new HashSet<Appointments>(0);
	private Set<CallLogs> callLogses = new HashSet<CallLogs>(0);

	public Patients() {
	}

	public Patients(Staff staff, Doctors doctors, String reportNumber) {
		this.staff = staff;
		this.doctors = doctors;
		this.reportNumber = reportNumber;
	}

	public Patients(Staff staff, Doctors doctors, String firstName,
			String lastName, String reportNumber, String phoneNumber,
			String address, String injury, Date dateOfCrash,
			String otherPassengers, String notes,
			Set<Appointments> appointmentses, Set<CallLogs> callLogses) {
		this.staff = staff;
		this.doctors = doctors;
		this.firstName = firstName;
		this.lastName = lastName;
		this.reportNumber = reportNumber;
		this.phoneNumber = phoneNumber;
		this.address = address;
		this.injury = injury;
		this.dateOfCrash = dateOfCrash;
		this.otherPassengers = otherPassengers;
		this.notes = notes;
		this.appointmentses = appointmentses;
		this.callLogses = callLogses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "caller_id", nullable = false)
	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctor_id", nullable = false)
	public Doctors getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Doctors doctors) {
		this.doctors = doctors;
	}

	@Column(name = "first_name", length = 60)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 60)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "report_number", nullable = false, length = 50)
	public String getReportNumber() {
		return this.reportNumber;
	}

	public void setReportNumber(String reportNumber) {
		this.reportNumber = reportNumber;
	}

	@Column(name = "phone_number", length = 15)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "injury", length = 45)
	public String getInjury() {
		return this.injury;
	}

	public void setInjury(String injury) {
		this.injury = injury;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_crash", length = 10)
	public Date getDateOfCrash() {
		return this.dateOfCrash;
	}

	public void setDateOfCrash(Date dateOfCrash) {
		this.dateOfCrash = dateOfCrash;
	}

	@Column(name = "other_passengers", length = 45)
	public String getOtherPassengers() {
		return this.otherPassengers;
	}

	public void setOtherPassengers(String otherPassengers) {
		this.otherPassengers = otherPassengers;
	}

	@Column(name = "notes", length = 600)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patients")
	public Set<Appointments> getAppointmentses() {
		return this.appointmentses;
	}

	public void setAppointmentses(Set<Appointments> appointmentses) {
		this.appointmentses = appointmentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patients")
	public Set<CallLogs> getCallLogses() {
		return this.callLogses;
	}

	public void setCallLogses(Set<CallLogs> callLogses) {
		this.callLogses = callLogses;
	}

}
