package com.deemsys.project.entity;

// Generated Feb 13, 2016 12:33:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Patients generated by hbm2java
 */
@Entity
@Table(name = "patients", catalog = "injury_new")
public class Patients implements java.io.Serializable {

	private Integer id;
	private Staff staff;
	private Clinics clinics;
	private Doctor doctors;
	private String localReportNumber;
	private String crashSeverity;
	private String reportingAgencyName;
	private String numberOfUnits;
	private String unitInError;
	private String country;
	private String cityVillageTownship;
	private String crashDate;
	private String timeOfCrash;
	private String unitNumber;
	private String name;
	private String dateOfBirth;
	private String gender;
	private String address;
	private Double latitude;
	private Double longitude;
	private String phoneNumber;
	private String injuries;
	private String emsAgency;
	private String medicalFacility;
	private String insuranceCompany;
	private String policyNumber;
	private String atFaultInsuranceCompany;
	private String atFaultPolicyNumber;
	private String crashReportFileName;
	private Integer patientStatus;
	private Set<Appointments> appointmentses = new HashSet<Appointments>(0);
	private Set<CallLogs> callLogses = new HashSet<CallLogs>(0);

	public Patients() {
	}

	public Patients(Staff staff, Clinics clinics, Doctor doctors,
			String localReportNumber, String crashSeverity,
			String reportingAgencyName, String numberOfUnits,
			String unitInError, String country, String cityVillageTownship,
			String crashDate, String timeOfCrash, String unitNumber,
			String name, String dateOfBirth, String gender, String address,
			Double latitude, Double longitude, String phoneNumber,
			String injuries, String emsAgency, String medicalFacility,String insuranceCompany,
			String policyNumber,String atFaultInsuranceCompany,String atFaultPolicyNumber,
			String crashReportFileName, Integer patientStatus) {
		this.staff = staff;
		this.clinics = clinics;
		this.doctors = doctors;
		this.localReportNumber = localReportNumber;
		this.crashSeverity = crashSeverity;
		this.reportingAgencyName = reportingAgencyName;
		this.numberOfUnits = numberOfUnits;
		this.unitInError = unitInError;
		this.country = country;
		this.cityVillageTownship = cityVillageTownship;
		this.crashDate = crashDate;
		this.timeOfCrash = timeOfCrash;
		this.unitNumber = unitNumber;
		this.name = name;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.address = address;
		this.latitude = latitude;
		this.longitude = longitude;
		this.phoneNumber = phoneNumber;
		this.injuries = injuries;
		this.emsAgency = emsAgency;
		this.medicalFacility = medicalFacility;
		this.crashReportFileName = crashReportFileName;
		this.patientStatus = patientStatus;
		this.insuranceCompany=insuranceCompany;
		this.policyNumber=policyNumber;
		this.atFaultInsuranceCompany=atFaultInsuranceCompany;
		this.atFaultPolicyNumber=atFaultPolicyNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "caller_id")
	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clinic_id")
	public Clinics getClinics() {
		return this.clinics;
	}

	public void setClinics(Clinics clinics) {
		this.clinics = clinics;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctor_id")
	public Doctor getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Doctor doctors) {
		this.doctors = doctors;
	}

	@Column(name = "local_report_number", length = 100)
	public String getLocalReportNumber() {
		return this.localReportNumber;
	}

	public void setLocalReportNumber(String localReportNumber) {
		this.localReportNumber = localReportNumber;
	}

	@Column(name = "crash_severity", length = 100)
	public String getCrashSeverity() {
		return this.crashSeverity;
	}

	public void setCrashSeverity(String crashSeverity) {
		this.crashSeverity = crashSeverity;
	}

	@Column(name = "reporting_agency_name", length = 100)
	public String getReportingAgencyName() {
		return this.reportingAgencyName;
	}

	public void setReportingAgencyName(String reportingAgencyName) {
		this.reportingAgencyName = reportingAgencyName;
	}

	@Column(name = "number_of_units", length = 100)
	public String getNumberOfUnits() {
		return this.numberOfUnits;
	}

	public void setNumberOfUnits(String numberOfUnits) {
		this.numberOfUnits = numberOfUnits;
	}

	@Column(name = "unit_in_error", length = 100)
	public String getUnitInError() {
		return this.unitInError;
	}

	public void setUnitInError(String unitInError) {
		this.unitInError = unitInError;
	}

	@Column(name = "country", length = 100)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "city_village_township", length = 100)
	public String getCityVillageTownship() {
		return this.cityVillageTownship;
	}

	public void setCityVillageTownship(String cityVillageTownship) {
		this.cityVillageTownship = cityVillageTownship;
	}

	@Column(name = "crash_date", length = 100)
	public String getCrashDate() {
		return this.crashDate;
	}

	public void setCrashDate(String crashDate) {
		this.crashDate = crashDate;
	}

	@Column(name = "time_of_crash", length = 100)
	public String getTimeOfCrash() {
		return this.timeOfCrash;
	}

	public void setTimeOfCrash(String timeOfCrash) {
		this.timeOfCrash = timeOfCrash;
	}

	@Column(name = "unit_number", length = 100)
	public String getUnitNumber() {
		return this.unitNumber;
	}

	public void setUnitNumber(String unitNumber) {
		this.unitNumber = unitNumber;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "date_of_birth", length = 100)
	public String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "gender", length = 100)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "address", length = 300)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "latitude")
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude")
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "phone_number", length = 100)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "injuries", length = 100)
	public String getInjuries() {
		return this.injuries;
	}

	public void setInjuries(String injuries) {
		this.injuries = injuries;
	}

	@Column(name = "ems_agency", length = 100)
	public String getEmsAgency() {
		return this.emsAgency;
	}

	public void setEmsAgency(String emsAgency) {
		this.emsAgency = emsAgency;
	}

	@Column(name = "medical_facility", length = 100)
	public String getMedicalFacility() {
		return this.medicalFacility;
	}

	public void setMedicalFacility(String medicalFacility) {
		this.medicalFacility = medicalFacility;
	}
	
	
	@Column(name = "insurance_company", length = 100)
	public String getInsuranceCompany() {
		return insuranceCompany;
	}

	public void setInsuranceCompany(String insuranceCompany) {
		this.insuranceCompany = insuranceCompany;
	}

	@Column(name = "policy_number", length = 100)
	public String getPolicyNumber() {
		return policyNumber;
	}

	public void setPolicyNumber(String policyNumber) {
		this.policyNumber = policyNumber;
	}

	@Column(name = "at_fault_insurance_company", length = 100)
	public String getAtFaultInsuranceCompany() {
		return atFaultInsuranceCompany;
	}

	public void setAtFaultInsuranceCompany(String atFaultInsuranceCompany) {
		this.atFaultInsuranceCompany = atFaultInsuranceCompany;
	}

	@Column(name = "at_fault_policy_number", length = 100)
	public String getAtFaultPolicyNumber() {
		return atFaultPolicyNumber;
	}

	public void setAtFaultPolicyNumber(String atFaultPolicyNumber) {
		this.atFaultPolicyNumber = atFaultPolicyNumber;
	}

	@Column(name = "crash_report_file_name", length = 800)
	public String getCrashReportFileName() {
		return this.crashReportFileName;
	}

	public void setCrashReportFileName(String crashReportFileName) {
		this.crashReportFileName = crashReportFileName;
	}

	@Column(name = "patient_status")
	public Integer getPatientStatus() {
		return this.patientStatus;
	}

	public void setPatientStatus(Integer patientStatus) {
		this.patientStatus = patientStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patients")
	public Set<Appointments> getAppointmentses() {
		return this.appointmentses;
	}

	public void setAppointmentses(Set<Appointments> appointmentses) {
		this.appointmentses = appointmentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patients")
	public Set<CallLogs> getCallLogses() {
		return this.callLogses;
	}

	public void setCallLogses(Set<CallLogs> callLogses) {
		this.callLogses = callLogses;
	}
	
	

}
