package com.deemsys.project.entity;

// Generated 14 Nov, 2017 6:37:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientNearbyClinicSearchResultId generated by hbm2java
 */
@Embeddable
public class PatientNearbyClinicSearchResultId implements java.io.Serializable {

	private String patientId;
	private int clinicId;

	public PatientNearbyClinicSearchResultId() {
	}

	public PatientNearbyClinicSearchResultId(String patientId, int clinicId) {
		this.patientId = patientId;
		this.clinicId = clinicId;
	}

	@Column(name = "patient_id", nullable = false, length = 32)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "clinic_id", nullable = false)
	public int getClinicId() {
		return this.clinicId;
	}

	public void setClinicId(int clinicId) {
		this.clinicId = clinicId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PatientNearbyClinicSearchResultId))
			return false;
		PatientNearbyClinicSearchResultId castOther = (PatientNearbyClinicSearchResultId) other;

		return ((this.getPatientId() == castOther.getPatientId()) || (this
				.getPatientId() != null && castOther.getPatientId() != null && this
				.getPatientId().equals(castOther.getPatientId())))
				&& (this.getClinicId() == castOther.getClinicId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPatientId() == null ? 0 : this.getPatientId().hashCode());
		result = 37 * result + this.getClinicId();
		return result;
	}

}
