package com.deemsys.project.entity;

// Generated Feb 13, 2016 12:33:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "injury_new")
public class Users implements java.io.Serializable {

	private Integer userId;
	private String username;
	private String password;
	private Integer isEnable;
	private Set<Staff> staffs = new HashSet<Staff>(0);
	private Set<LawyerAdmin> lawyerAdmins = new HashSet<LawyerAdmin>(0);
	private Set<Lawyers> lawyerses = new HashSet<Lawyers>(0);
	private Set<UserRoleMapping> userRoleMappings = new HashSet<UserRoleMapping>(
			0);

	public Users() {
	}

	public Users(String username, String password, Integer isEnable,
			Set<Staff> staffs, Set<LawyerAdmin> lawyerAdmins,
			Set<Lawyers> lawyerses, Set<UserRoleMapping> userRoleMappings) {
		this.username = username;
		this.password = password;
		this.isEnable = isEnable;
		this.staffs = staffs;
		this.lawyerAdmins = lawyerAdmins;
		this.lawyerses = lawyerses;
		this.userRoleMappings = userRoleMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "is_enable")
	public Integer getIsEnable() {
		return this.isEnable;
	}

	public void setIsEnable(Integer isEnable) {
		this.isEnable = isEnable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Staff> getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Set<Staff> staffs) {
		this.staffs = staffs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<LawyerAdmin> getLawyerAdmins() {
		return this.lawyerAdmins;
	}

	public void setLawyerAdmins(Set<LawyerAdmin> lawyerAdmins) {
		this.lawyerAdmins = lawyerAdmins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Lawyers> getLawyerses() {
		return this.lawyerses;
	}

	public void setLawyerses(Set<Lawyers> lawyerses) {
		this.lawyerses = lawyerses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserRoleMapping> getUserRoleMappings() {
		return this.userRoleMappings;
	}

	public void setUserRoleMappings(Set<UserRoleMapping> userRoleMappings) {
		this.userRoleMappings = userRoleMappings;
	}

}
