package com.deemsys.project.entity;

// Generated 23 May, 2017 4:20:19 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserExportPreferencesId generated by hbm2java
 */
@Embeddable
public class UserExportPreferencesId implements java.io.Serializable {

	private int userId;
	private Integer fieldId;
	private Integer sequenceNo;
	private Integer status;

	public UserExportPreferencesId() {
	}

	public UserExportPreferencesId(int userId) {
		this.userId = userId;
	}

	public UserExportPreferencesId(int userId, Integer fieldId,
			Integer sequenceNo, Integer status) {
		this.userId = userId;
		this.fieldId = fieldId;
		this.sequenceNo = sequenceNo;
		this.status = status;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "field_id")
	public Integer getFieldId() {
		return this.fieldId;
	}

	public void setFieldId(Integer fieldId) {
		this.fieldId = fieldId;
	}

	@Column(name = "sequence_no")
	public Integer getSequenceNo() {
		return this.sequenceNo;
	}

	public void setSequenceNo(Integer sequenceNo) {
		this.sequenceNo = sequenceNo;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserExportPreferencesId))
			return false;
		UserExportPreferencesId castOther = (UserExportPreferencesId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getFieldId() == castOther.getFieldId()) || (this
						.getFieldId() != null && castOther.getFieldId() != null && this
						.getFieldId().equals(castOther.getFieldId())))
				&& ((this.getSequenceNo() == castOther.getSequenceNo()) || (this
						.getSequenceNo() != null
						&& castOther.getSequenceNo() != null && this
						.getSequenceNo().equals(castOther.getSequenceNo())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result
				+ (getFieldId() == null ? 0 : this.getFieldId().hashCode());
		result = 37
				* result
				+ (getSequenceNo() == null ? 0 : this.getSequenceNo()
						.hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
